[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonsless"
decorations = "None" #for linux also

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "Inconsolata Nerd Font Mono"

size = 14

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
{ key = "F", mods = "Control|Shift", action = "ToggleFullscreen"},
{ key = "L", mods = "Control|Shift", action = "ToggleMaximized"}
]


